### ISSUE TITLE
How to setup proxy?

### ISSUE THREAD

**Issue by guotie** [knq/chromedp#1]
This is a soooooooo great job! I love it.

And I have a question: How to setup proxy?

**Comment by kenshaw** [comment]
You need to configure `chromedp/runner/Runner` to use the Proxy flag:

```go
c, err := chromedp.New(ctxt, chromedp.WithRunnerOptions(
    runner.Proxy(`http://localhost:8000/`),
))
```

**Comment by milgov** [comment]
How it use at now? `runner` package does not exists.

**Comment by mvdan** [comment]
There was a refactor. If you want to use the example above as-is, use v0.1. Otherwise, see https://godoc.org/github.com/chromedp/chromedp#ProxyServer.
