### ISSUE TITLE
dumb question: where do I get headless_shell?

### ISSUE THREAD

**Issue by kmanley** [knq/chromedp#100]
Sorry for the dumb question, I've googled around and can't seem to figure out where to get headless_shell. I currently run chrome with the --headless flag, but I gather there is some binary headless_shell that is smaller/faster to startup that works in a similar way. Any pointers appreciated.

**Comment by kmanley** [comment]
(for Ubuntu 16.04 LTS by the way)

**Comment by kenshaw** [comment]
You need to build it from the Chromium source tree, or download a pre-built version of it. If you check out the travis-ci config for `chromedp` you can see how the unit tests download a pre-built version of `headless_shell`.

(note: I'm purposefully not directly linking to the pre-built versions of `headless_shell`, as I have no intention/bandwidth for supporting `headless_shell` directly, however anyone who wants to download the binaries I've made available for `chromedp` is free to do so)

**Comment by kmanley** [comment]
Thanks!
