### ISSUE TITLE
Remote headless chrome

### ISSUE THREAD

**Issue by mrminute** [knq/chromedp#108]
Is it possible to use a headless chrome running on a remote host?

**Comment by martint17r** [comment]
Yes, take a look at the headless example in L23
https://github.com/knq/chromedp/blob/50c2d576db8913bb0f0d29dc148a1d8886c11c80/examples/headless/main.go#L23

and use a client.Option to give an URL:
https://github.com/knq/chromedp/blob/50c2d576db8913bb0f0d29dc148a1d8886c11c80/client/client.go#L300

**Comment by kenshaw** [comment]
Yes, as @martint17r has pointed out. You just need to point the client to connect to the remote host.
