### ISSUE TITLE
formal way of headless option in cdp or runner?

### ISSUE THREAD

**Issue by stephencheng** [knq/chromedp#109]
I am hitting the issue that it won't start it up and spin up the headless chrome unless I apply the hack below:

My hack is in runner.go file

	// set default Chrome options if exec-path not provided
	if _, ok := cliOpts["exec-path"]; !ok {
		cliOpts["exec-path"] = findChromePath()
		for k, v := range map[string]interface{}{
			"no-first-run":             true,
			"headless":             true, //<=============my hack============
			"no-default-browser-check": true,
			"remote-debugging-port":    9222,
		} {
			if _, ok := cliOpts[k]; !ok {
				cliOpts[k] = v
			}
		}
	}

I tried to find a way for the formal supporting this, it seems the only option might be:

// Headless is the Chrome command line option to set the default settings for
// running the headless_shell executable. If path is empty, then an attempt
// will be made to find headless_shell on the path.
func Headless(path string, port int) CommandLineOption {
	if path == "" {
		path, _ = exec.LookPath("headless_shell")
	}

	return func(m map[string]interface{}) error {
		m["exec-path"] = path
		m["remote-debugging-port"] = port

		if os.Getenv("CHROMEDP_NO_SANDBOX") != "" {
			m["no-sandbox"] = true
		}

		return nil
	}
}

I have known from the reported issues that this Headless shell thing is kind of past thing, am I right?

Can we add/mod to support the headless option so that the simple example will run?

**Comment by smaragden** [comment]
I wonder about this aswell. I have been trying all different flag combinations.
But i can't get it to run headless. This is how i set up the cdp instance:

```
c, err := cdp.New(
	ctxt, cdp.WithRunnerOptions(
		runner.Flag("no-sandbox", true),
		runner.ExecPath("/usr/bin/google-chrome"),
		runner.Flag("headless", true),
		runner.Flag("disable-gpu", true),
		runner.Port(9222),
	),
)
```

When i check the running process the flags seem fine.
But i get:
```
2017/09/12 01:11:05 error: could not perform (attributeModified) operation on node 10 (wait node): timeout waiting for node `10`
2017/09/12 01:11:05 error: could not perform (attributeModified) operation on node 12 (wait node): timeout waiting for node `12`
```
Thanks in advance

**Comment by stephencheng** [comment]
@smaragden I managed to have hacked it and worked, but I doubt this would be acceptable as merge request because there are other ongoing headless shell option to clean up at the moment.

To be specific, you need to patch this part:

`     53         // set default Chrome options if exec-path not provided
     54         if _, ok := cliOpts["exec-path"]; !ok {
     55                 cliOpts["exec-path"] = findChromePath()
     56                 for k, v := range map[string]interface{}{
     57                         "headless":             true,
     58                         "no-first-run":             true,
     59                         "disable-gpu":             true,
     60                         "no-default-browser-check": true,
     61                         "remote-debugging-port":    9222,
     62                 } {
     63                         if _, ok := cliOpts[k]; !ok {
     64                                 cliOpts[k] = v
     65                         }
     66                 }
     67         }`

**Comment by LeMoussel** [comment]
Why don't use `WithRunnerOptions`  like this [How to create and launch chrome instance by disabling security option?](https://github.com/knq/chromedp/issues/119#issuecomment-332049510)
