### ISSUE TITLE
how to open chrome with specific user profile

### ISSUE THREAD

**Issue by AmrAlfoly** [knq/chromedp#110]
i need to start chrome with a specific user profile
how can i do that ?

**Comment by kenshaw** [comment]
Please see [the various chrome cli options available here](http://peter.sh/experiments/chromium-command-line-switches/).

I typically make use of the `--user-data-dir` switch when I intend to reuse profiles:
```sh
google-chrome --user-data-dir=/path/to/some-directory
```

**Comment by AmrAlfoly** [comment]
i meant to start google chrome using chromedp package with a specific profile
