### ISSUE TITLE
how to test the selector?

### ISSUE THREAD

**Issue by stephencheng** [knq/chromedp#111]
sorry, this might be a very beginner question and I am hoping someone could kindly give me a hint

I wonder what's the selector format/standard chromedp is taking, I tested clicking a button by using:
		cdp.Click(`#login`, cdp.NodeVisible),
this works

In another site, for the click button without id, I use below css selector:

#customer_login :input[type=submit]

It works in chrom's console: 

$("#customer_login :input[type=submit]")

The click also works in console: $("#customer_login :input[type=submit]").click()

However in my go code as below, it just keep searching until: 

2017/08/26 17:48:34 <- {"id":1788,"method":"DOM.performSearch","params":{"query":"#customer_login :input[type=submit]:first-child"}}
2017/08/26 17:48:34 -> {"id":1788,"result":{"searchId":"74031.1795","resultCount":0}}
2017/08/26 17:48:34 <- {"id":1789,"method":"DOM.performSearch","params":{"query":"#customer_login :input[type=submit]:first-child"}}
2017/08/26 17:48:34 -> {"id":1789,"result":{"searchId":"74031.1796","resultCount":0}}
2017/08/26 16:27:28 context deadline exceeded

code I used:
		cdp.Click(`#customer_login :input[type=submit]:first-child`, cdp.NodeVisible),

What's wrong with this line of code?

Thanks

**Comment by stephencheng** [comment]
All right, it works with #id, for other type of selector like this:

body > pre

it loops forever. Which option should I use instead?

**Comment by randycahyana** [comment]
By default chromedp

**Comment by randycahyana** [comment]
By default chromedp would apply [BySearch](https://godoc.org/github.com/knq/chromedp#BySearch) option if there is not option specified. 
[ByQuery](https://godoc.org/github.com/knq/chromedp#ByQuery)

**Comment by stephencheng** [comment]
@randycahyana 
unfortunately for my case, below two cases all work

		// cdp.Click(`#customer_login > div:nth-child(6) > input`, cdp.NodeVisible, cdp.ByQuery),
		// cdp.Click(`#customer_login > div:nth-child(6) > input`, cdp.NodeVisible, cdp.ByID),

I like chromedp, however without too much docs/tutorials and replies from developers, this is too hard .........

I am hoping someone could do something about it

**Comment by stephencheng** [comment]
@randycahyana 

I tested based on your suggestion, it worked for example.org

Thanks
