### ISSUE TITLE
How to apply proxy url with headless chrome enabled

### ISSUE THREAD

**Issue by Mrhyuan** [knq/chromedp#113]

**Comment by kenshaw** [comment]
Chrome supports the same command line options when being used with `--headless`. Simply pass whatever `--proxy` CLI options are provided. Please see this handy table of available CLI options: https://peter.sh/experiments/chromium-command-line-switches/

Please note you use this in conjunction with either `WithRunnerOptions` or by invoking your own Chrome headless process and connecting the `chromedp.CDP` type to it.
