### ISSUE TITLE
how to send key without focus?

### ISSUE THREAD

**Issue by stephencheng** [knq/chromedp#114]
Currently, you will have to use a sel as first argument to locate the foucsable element so that you can send the key.

I am encountering a issue to send the key to a jira description box, which is somehow rendered by javascript. I need to click on the edit box first to gain the foucs then key in whatever contents. With: 
1. 			cdp.DoubleClick(`#description-val > div`, cdp.NodeVisible),
2.			cdp.SendKeys(`#description-val > div`, "\naoeu\n\ntest1\n\nblah2\n\n\t\t\t"),

It just does not work, as I already have the foucs gained on the 1st line, it fails on the 2nd line due to: 

2017/08/30 10:33:25 -> {"error":{"code":-32000,"message":"Element is not focusable"},"id":79}

Anyway to tackle this issue or adding support for it?

**Comment by kenshaw** [comment]
`SendKeys` is for `input` elements. Not for `div`'s, as it synthesizes keystrokes for form input elements. Part of this is necessitates doing calling focus on that element. You can change your selector to select the actual form input field being used on JIRA's HTML.
