### ISSUE TITLE
check for an element is present in the page

### ISSUE THREAD

**Issue by AmrAlfoly** [knq/chromedp#120]
how can i check for an element is present in the page ?
i need this so i can make dictions if the app will do one thing or the other

**Comment by yogesh-desai** [comment]
Hello AmrAlfoly,

I was able to get the webyclip-widget-3 element on the webpage by using below function. I have used the JavaScript in EvaluateAsDevTools() function. The chrome dev tools (console) will definitely get handy in these cases. You can modify it as per your requirement. Hope this helps you. Let me know if it helps, you can then close the issue.

Please try something like this,
```
// isPresent checks the existance of webyclip-widget-3 element.
func isPresent(url string, res *[]byte) cdp.Tasks {

	return cdp.Tasks{
		cdp.Navigate(url),
		cdp.Sleep(15 * time.Second),
		cdp.EvaluateAsDevTools("if (document.getElementById('webyclip-thumbnails')) {document.getElementById('webyclip-thumbnails').childElementCount;} else {console.log('0')}", res),
	}

}
```

**Comment by AmrAlfoly** [comment]
@yogesh-desai  thx for your try
but it didn't give me what i asked for

**Comment by yogesh-desai** [comment]
@AmrAlfoly : You need to modify the query as per your requirements. Could you give web page link and what exactly you want? What have you tired? you can give a snippet may be to mention what went wrong.
As specific questions will be even better to address and solve.

**Comment by AmrAlfoly** [comment]
[https://stackoverflow.com/questions/46438339/how-can-i-check-for-an-element-is-present-in-the-page-using-golang-knq-chromedp](url)

**Comment by yogesh-desai** [comment]
Please check my answer submitted on the [Stackoverflow](https://stackoverflow.com/questions/46438339/how-can-i-check-for-an-element-is-present-in-the-page-using-golang-knq-chromedp/46471972#46471972). 

Also, The given link by you is not working somehow. I need to find your question with the id 46438339. Please make sure it works.

**Comment by yin1999** [comment]
I have a better way to deal with this.  
You can use **chromedp.EvaluateAsDevTools** to get some information about the element that may present.  
If the **ClassName** is **""**, it means the element is not present; else, it means the element is present.

The following is a try on [Bing](https://cn.bing.com/)

    err := chromedp.Run(ctx,
		chromedp.Navigate(`https://cn.bing.com/`),
		chromedp.EvaluateAsDevTools(`document.querySelector("#aRmsDefer")`, &res))
	if res.ClassName != "" {
		fmt.Println("Exists: #aRmsDefer.")
	} else {
		fmt.Println("Not exists: #aRmsDefer.")
	}
	err = chromedp.Run(ctx,
		chromedp.Navigate(`https://cn.bing.com/`),
		chromedp.EvaluateAsDevTools(`document.querySelector("#post")`, &res))
	if err != nil {
		fmt.Println(err)
	}
	if res.ClassName != "" {
		fmt.Println("Exists: #post.")
	} else {
		fmt.Println("Not exists: #post.")
	}

**Comment by mvdan** [comment]
In case anyone follows this thread, just want to add that `chromedp.Nodes(yourSelector, &nodes, chromedp.AtLeast(0))` is what I personally prefer. If the slice ends up empty, then there weren't any matches.

**Comment by yin1999** [comment]
> In case anyone follows this thread, just want to add that `chromedp.Nodes(yourSelector, &nodes, chromedp.AtLeast(0))` is what I personally prefer. If the slice ends up empty, then there weren't any matches.

Thanks for your suggestion, it's really useful.

**Comment by kylebevans** [comment]
mvdan's answer will return a QueryAction that you then have to execute with a .Do. Here is an example:

```
var nodes []*cdp.Node
ctx := context.Background()
chromedp.Nodes(".someClass", &nodes, chromedp.ByQuery, chromedp.AtLeast(0)).Do(ctx)
if len(nodes) != 0 {
  // someClass exists, do something
}
```
Sorry to comment on an old, closed issue, but hopefully this will help other folks that get here from Google.

**Comment by ZekeLu** [comment]
@kylebevans Instead of calling `Do`, you should use `chromedp.Run` to run actions. And please note that you should use a context returned from `chromedp.NewContext`.
