### ISSUE TITLE
Running multiple instances of CDP with headless-shell 

### ISSUE THREAD

**Issue by Jbegley1995** [knq/chromedp#123]
First of all, great package! I was using PhantomJS and getting random issues, its good to find an alternative.

The error i'm running into looks like this `could not create handler for 2a6cb825-dd55-49d4-bfbb-d5d4d8ac667b (``): malformed ws or wss URL`. This could be from my lack of understanding the package, but I have put in some time trying to fix this, and I can't figure it out. I'm using the headless shell example and the docker headless-chrome instance. Here's what my code looks like, and keep in mind this is getting called multiple times and fails on cdp.New inside of AddTarget for every one after the first: 

This creates my cdp instance. (context is declared above)

```
func createHeadless() *cdp.CDP {
		cl := client.New()
		tgts := cl.WatchPageTargets(ctxt)
		// create chrome
		c, err := cdp.New(ctxt, cdp.WithTargets(tgts))
		if err != nil {
			log.Fatal(err)
		}
		return c
}
```

this is where it is used.
```
func (batchReport BatchReportInfo) callHeadless(path string, token string) string {
	lock.Lock()
	defer lock.Unlock()
	c := createHeadless()
	// run task list
	var res string
	err := c.Run(ctxt, batchReport.getReportTasks(path, &res, token))

	return res
}
```

**Comment by kenshaw** [comment]
I'm not really clear why you're trying to instantiate the targets directly? Sure the `WatchPageTargets` API is available to use, but if you haven't read the code closely, I would not suggest using that. The reason that API is public is because client.Target is an interface, so that it is possible to use the `CDP` type with non `chromedp/client` based Targets. It looks like you're using the default client / path, so why not just use `chromedp.New()`? Are you trying to use this with something other than Chrome?

**Comment by Jbegley1995** [comment]
It actually works great with chrome when I'm using it on Windows without targets. The issue is that I need to run with Amazon linux so I can't actually get chrome. If you have any solution that would work with Amazon linux that can be called more than once that would solve my problem. I appriciate the quick feedback

**Comment by Jbegley1995** [comment]
Thanks for the help, for anyone that has amazon linux that was having trouble with this and was trying to use the precompiled headless shell with targets, don't. Instead I just got chrome 58 on my machine (since chrome 59 and greater is not supported on CentOS derivatives) and used chromedp.New() like was suggested above.
