### ISSUE TITLE
Windows: c:\temp doesn't exist

### ISSUE THREAD

**Issue by tdewolff** [knq/chromedp#13]
This is fixed by creating a directory called c:\temp, but this is not the usual tmp directory for Windows. It should be `%USERPROFILE%\AppData\Local\` or user assignable.

**Comment by kenshaw** [comment]
Hi, thanks for the input. Would appreciate a pull request if you could manage it! For the record, it is configurable by setting the UserDataDir flag on the runner.

**Comment by tdewolff** [comment]
Oh I see now, still trying to grasp how the code is structured. Thanks!
