### ISSUE TITLE
what's most effective way to tell if a selector exist or not

### ISSUE THREAD

**Issue by stephencheng** [knq/chromedp#135]
like what's looked like in casperjs:

```

if(casper.exists('#ctl00_BodyPlaceHolder_QuoteSearchView1_ucShareQuote_lblIndicativePrice_field')){ 
    do_something()
}else{
    do_something_else()
}



```
I understand that I could wait visible and then check error or use timeout to achieve similar, but I don't want to use these sort of expensive steps.

Do we have any similar and simple thing in CDP for it? or you have better ideas than what I listed above.

Thanks

**Comment by stephencheng** [comment]
well, I will just write up a task function with timeout to make it

**Comment by nicolasassi** [comment]
Hi! I'm facing the same problem! Could you share the solution you found?

**Comment by daved** [comment]
This seems like a glaring hole. Are we each missing something more obvious?
