### ISSUE TITLE
docker run remote console does not show

### ISSUE THREAD

**Issue by stephencheng** [knq/chromedp#138]
I used: docker run -d -p 9222:9222 --rm --name chrome-headless knqz/chrome-headless for the test cases, it worked fine. However when I use browser to check the remote console gui on: http://localhost:9222, it won't show the gui, rather saying:404 Not Found The resource could not be found.

Am I missing any step? How did you do it in your case?

**Comment by kenshaw** [comment]
You are likely not using the correct version of Google Chrome -- either it is too old, or the Devtools you're using won't work with it.
