### ISSUE TITLE
can't disable log

### ISSUE THREAD

**Issue by AmrAlfoly** [knq/chromedp#143]
i am creating a new instance of chromedp using cdp.runner options so i can specify a user dir for chrome to use and i am not using cdp.WithLog()
but the log keeps printing messages that i don't care about and don't want them to be present in my terminal window
how can i stop it ?
`c, err := cdp.New(ctxt, cdp.WithRunnerOptions(runner.Path("/usr/bin/google-chrome"), runner.UserDataDir(sysUser.HomeDir+"/.config/google-chrome/"), runner.WindowSize(1000, 800)))
`

**Comment by kenshaw** [comment]
Pass a func that does nothing to the `WithLog*` func's.
