### ISSUE TITLE
Target functions don't work properly

### ISSUE THREAD

**Issue by korovkinand** [knq/chromedp#144]
Functions CloseByID and CloseByIndex do nothing, cause they are not implemented
```
func (c *CDP) CloseByIndex(i int) Action {
	return ActionFunc(func(ctxt context.Context, h cdp.Handler) error {
		return nil
	})
}

func (c *CDP) CloseByID(id string) Action {
	return ActionFunc(func(ctxt context.Context, h cdp.Handler) error {
		return nil
	})
}
```

GoDoc says: 
> NewTarget is an action that creates a new Chrome target, and sets it as the active target.

But it only creates a new target without activation, so it is necessary to invoke SetHandler function for manual activation. 

NewTargetWithURL function is present in the code but it's commented. 

Your library is awesome and we are happy using it in our project, but can you please fix these functions.

We also consider using pool of instances but afraid that it will consume more system resources, we need to simultaneously load 15-20 sites

**Comment by jcrussell** [comment]
This seems to work for me... I keep track of what targets exist and close new ones periodically. Not sure if it's leaking handlers when I close the targets.

https://github.com/jcrussell/chromedp/tree/close-target
