### ISSUE TITLE
grab-headless_shell.sh no longer functional

### ISSUE THREAD

**Issue by lrstanley** [knq/chromedp#148]
just a heads up, looks like the account behind the binary-distributed compiled headless shell versions is no longer a thing.

```
liam:~$ curl -s https://storage.googleapis.com/docker-chrome-headless/latest.txt
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccountProblem</Code><Message>Your Google account is not currently enabled for this operation. Please check https://console.developers.google.com/billing to see if you have a past due balance or if the credit card (or other payment mechanism) on your account is expired. You can find additional information at https://developers.google.com/storage/docs/signup</Message><Details>The billing account for the requested project is disabled in state 'delinquent'</Details></Error>
```

not sure if there are any alternatives for easily grabbing a compiled version of the headless shell. looks like the `knqz/chrome-headless` docker image may be the best suggestion for folks at this time.

**Comment by kenshaw** [comment]
Too many people were using that for retrieving headless_shell. The bill last month was over $1,000 USD. I would have left it up if it were less than $100, but as it is, there are a bunch of bots out there that were setup to use the published artifacts. I haven't had time to switch to a different location yet.

**Comment by lrstanley** [comment]
Yikes!
