### ISSUE TITLE
Chrome version 62+

### ISSUE THREAD

**Issue by Samsimus12** [knq/chromedp#154]
The following error frequently appears in the terminal across all platforms: 
error: unhandled page event *page.EventLifecycleEvent

The settings tab also opens for every single key stroke on Mac. Very, very annoying. 

I've noticed this on all versions of Chrome 62 and above.

**Comment by piyushchauhan2011** [comment]
Is this resolved ? @kenshaw

**Comment by Samsimus12** [comment]
This is what I had to do with my local copy of this repo:

       kb/kb.go //Edit this file

       keyDown := input.DispatchKeyEventParams {
		Key:                   v.Key,
		Code:                  v.Code,
	 	NativeVirtualKeyCode:  v.Native, //Comment out this line
		WindowsVirtualKeyCode: v.Windows,
	}

I'm on a Mac and this fixed the issue with the error message as well as the settings tab repeatedly opening. Hope this helps.

Cheers
