### ISSUE TITLE
Your connection is not private / proceed anyway

### ISSUE THREAD

**Issue by hagna** [knq/chromedp#157]
How can chromedp proceed anyway even though chrome warns about ERR_CERT_AUTHORITY_INVALID?  As of now it does not load a page when this error occurs.

**Comment by kenshaw** [comment]
Please see the command line switch `--ignore-certificate-errors` -- https://peter.sh/experiments/chromium-command-line-switches/

Additionally, you can use the `Security` and `Network` domains to handle certificate errors. You will need to listen for the events, and handle them appropriately. Please see the DevTools Protocol documentation: https://chromedevtools.github.io/devtools-protocol/tot/Security/

**Comment by hagna** [comment]
--ignore-certificate-errors appears to have no effect

I don't see any Security.certificateError or any Security type events in the log, but I do see this event:

2017/12/20 09:53:41 -> {"method":"Page.interstitialShown","params":{}}
2017/12/20 09:53:41 unhandled page event *page.EventInterstitialShown

Is that the event that should be handled?

**Comment by 4ydx** [comment]
The following works:

```
  c, err := chromedp.New(                                                                                                             
    ctxt,                                                                                                                             
    chromedp.WithLog(log.Printf),                                                                                                     
    chromedp.WithRunnerOptions(runner.Flag("ignore-certificate-errors", "1")),                                                        
  )                                                                                                                                   
  if err != nil {                                                                                                                     
    log.Fatal(err)                                                                                                                    
  }  
```
