### ISSUE TITLE
question : which is faster cdp.ByQuery() vs cdp.BySearch() ?

### ISSUE THREAD

**Issue by AmrAlfoly** [knq/chromedp#158]
if the elements i am looking for can be found by css selector and by xpath 
which of cdp.ByQuery() or cdp.BySearch() is faster
and if the page has already loaded , what is the best time for the context timeout ?

**Comment by kenshaw** [comment]
I don't think they would perform much differently, and I wouldn't know if one was better than the other. The query type just gets sent to Chrome. May I suggest that this is a case of premature optimization? I can't imagine a scenario where running `ByQuery`/`BySearch` would be slower than waiting for the network to return data and for the rendering to complete.
