### ISSUE TITLE
Pool : fork/exec : no such file or directory

### ISSUE THREAD

**Issue by JalfResi** [knq/chromedp#16]
macOS Sierra 10.12.2
Chrome installed at the following location: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

Running the following using the path hard-coded into chromedp/runner/path_darwin.go:
$ open "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

Successfully opens Chrome instance, so path is correct.

From within my program, I cannot allocate from pool, resulting in the error message:
fork/exec : no such file or directory

Running the unit tests results in:

--- FAIL: TestNavigate (0.00s)
	chromedp_test.go:38: fork/exec : no such file or directory
FAIL
exit status 1
FAIL	github.com/knq/chromedp	0.023s

Let me know if you need more details.

P.S. The new Pool feature seems bang-on!

**Comment by kenshaw** [comment]
`Pool` at the moment only works with Chrome's `headless_shell`, which I believe at the moment will only compile on Linux. Will fix this in the future (ie, run unit tests with normal Chrome and/or make `headless_shell` binaries available for osx, and possibly make a separate Docker based Pool implementation).

**Comment by JalfResi** [comment]
Does that mean the target Chrome must be linux based, or that any program that uses chromedp/pool will have to be compiled and run on linux?

**Comment by JalfResi** [comment]
Scratch that, I'm an idiot. Just re-read your message :)

**Comment by JalfResi** [comment]
Apologies for commenting on a closed issue, but I've noticed that on line 80 of pool.go:

r.r, err = runner.New(append([]runner.CommandLineOption{
		runner.Headless("", r.port),
	}, opts...)...)

It adds Headless as a required option. Could that not be an option specified by the caller of Allocate? Have I missed something, or is there a reason why the pool only works with headless chrome? For testing my program, I was hoping to "switch" on headless at a later date and work with a "visual" chrome whilst developing...

**Comment by kenshaw** [comment]
Forgot to mention, you can pass a different `ExecPath` option to the `Pool.Allocate` func. I'm working on an OSX machine at the moment, and was able to get it to work with Chrome canary headless by specifying the following runner options:

```go
func TestNavigate(t *testing.T) {
     var err error

     c, err := pool.Allocate(defaultContext,
         runner.Flag("headless", true),
         runner.Flag("no-default-browser-check", true),
         runner.Flag("no-first-run", true),
         runner.ExecPath(`/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary`),
     )
```

I will make a point to change the code to better work cross platform for running the unit tests, in addition to alternately choosing different "pool options" such as "Docker pool" etc. At the moment, the unit tests obviously are not complete (I haven't even tried to start a comprehensive effort there, but it is very high on the list), as I was just trying to get the project "framed" correctly with unit tests, coverage, etc -- so the real focus with the unit tests was just to get them working in as light-weight of a format as possible for use with travis. For what it's worth, I'm writing up an article on using the package to do proper Go-style unit testing.

If you'd like to take a stab at fixing the cross platform issues, I'm always willing to consider high quality pull requests!

**Comment by JalfResi** [comment]
I only came across your project via golangweekly the other day - it is exactly what I need after struggling with WebDriver and Phantomjs for ages!

I will definitely be digging in deeper over the coming weeks as the code is excellent and clear. Thanks for the quick responses, really looking forward to digging in deep this weekend!

**Comment by kenshaw** [comment]
Great, hope it works for you! Hoping, also, at least in the Go world, to make WebDriver, PhantomJS, Selenium, a thing of the past.
