### ISSUE TITLE
Snapshot DOM

### ISSUE THREAD

**Issue by clanstyles** [knq/chromedp#19]
How would we snapshop the DOM as it was? But this doesn't give us an actual snapshot of a DOM?

```
func Nodes(sel interface{}, nodes *[]*cdp.Node, opts ...QueryOption) Action
func NodeIDs(sel interface{}, ids *[]cdp.NodeID, opts ...QueryOption) Action
```

**Comment by kenshaw** [comment]
What do you mean by "snapshot" of the DOM? If you want the full DOM tree, then you just need to call `chromedp/cdp/dom/getDocument`. If you want the actual HTML, you need to use a network command. Neither of this is built in at the moment.

**Comment by clanstyles** [comment]
Yeah I'd like a screenshot of the DOM for further processing. You have ByID and ByQuery but not "ByTag" which would be "body" that seems easiest.
