### ISSUE TITLE
TargetHandler does not implement cdp.Handler

### ISSUE THREAD

**Issue by JalfResi** [knq/chromedp#21]
Trying to build my program against my fork of chromedp, get the following error:

chromedp/chromedp.go:137: cannot use h (type *TargetHandler) as type cdp.Handler in assignment:
        *TargetHandler does not implement cdp.Handler (wrong type for Execute method)
                have Execute(context.Context, cdp.MethodType, easyjson.Marshaler, easyjson.Unmarshaler) error
                want Execute(context.Context, cdp.MethodType, easyjson.RawMessage) <-chan interface {}

Is this something currently in flux?

**Comment by kenshaw** [comment]
There was a big set of changes, yes, but the API / everything should be the same.

I would check the following:

1) See if you checked out the repository to a path other than `github.com/knq/chromedp` and made local changes to `chromedp/*.go` changing the paths. My guess is then that you didn't change the paths after merging/rebasing the latest commits.

2) If the above isn't the issue, check if there was a merge conflict for some reason, that caused some of the updates to not be applied correctly.

3) Possibly you have other local modifications that are pointing to two separate repositories.

If you're having problems still, doing a fresh checkout of chromedp and then trying your code against that might help illuminate what the problem is. I'm fairly certain though it's just a pathing issue.

**Comment by JalfResi** [comment]
Thanks a lot for the tips. I'll give them all a go in the morning. I just wanted to confirm that the master branch wasn't broken, so thats good!

Closing this issue.

**Comment by JalfResi** [comment]
For others that come across something similar; I hadn't set things up properly for contributing to a Go  project.

Simply following the example here:
 
http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html
 
Now work in the checkout original branch (not your fork) and create a branch for your change, and push your branch+changes to your github remote with “git push fork”
 
From there, you can raise a pull request back to the original project
 
So the secret is – Work in the original (forkee) repo and push changes to your remote fork.
 
This way, all the go import paths remain and don’t need changing.
 
Finally, to test your branch changes, use “go install” to override the original master compiled package and import into your pet project with your branched changes for testing.

**Comment by kenshaw** [comment]
Yes, that's the way to do development with Git in general, but especially with go projects. The commands are like this:

```sh
# check out latest code base
$ go get -u github.com/knq/chromedp

# move to working directory
$ cd $GOPATH/src/github.com/knq/chromedp

### ON GITHUB, NOW FORK THE REPOSITORY ###

# add ***FORKED*** repository as new remote
$ git remote add my-github-user-name https://github.com/my-github-user-name/chromedp.git

# checkout new branch based off knq's (ie, the "origin") master branch:
$ git checkout -b name-of-thing-to-fix origin/master

### MAKE CHANGES ###

# commit your changes to your name-of-thing-to-fix branch
$ git commit -m 'My commit fixes'

# push your name-of-thing-to-fix branch to your my-github-user-name remote:
$ git push my-github-user-name name-of-thing-to-fix

### ON GITHUB, CREATE PULL REQUEST FOR name-of-thing-to-fix BRANCH
```

For reference, the way then that pull request can be merged into master, is for me as the project maintainer, just a few / simple command lines:
```sh
$ cd $GOPATH/src/github.com/knq/chromedp

# add remote
$ git remote add some-other-github-user https://github.com/some-other-github-user/chromedp.git

# fetch
$ git fetch some-other-github-user

# compare changes from master with named branch 'issue-to-fix'
$ git diff origin/master some-other-github-user/issue-to-fix

# add changes
$ git rebase some-other-github-user/issue-to-fix
```

This avoids issues with merge commits and all that kind of stuff. Apologies if the above is not 100% perfect, I did it from memory -- but considering I do this about 10x/day, I'm pretty certain its right, but there might be typos or some such ...
