### ISSUE TITLE
Evaluate javascript ?

### ISSUE THREAD

**Issue by howesteve** [knq/chromedp#3]
Hello,

Is there a way to evaluate javascript code ? It's a fairly common task among all browser automation tools I used, but I didn't find it in chromedp (and the lack of docs didn't help either).

Thanks,
Howe

**Comment by kenshaw** [comment]
Yes, use the chromedp.Evaluate() action in conjuction with the chromedp/runner/Runner. Or use chromedp/cdp/runtime.Evaluate() with the frame handler.

**Comment by howesteve** [comment]
Oh, thanks. I've missed that.

Howe

**Comment by yogesh-desai** [comment]
Thank you. After giving a thought for some time, I got it.
