### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by wirepair** [knq/chromedp#31]
go version: 1.8 (ubuntu 16)

go test -v
=== RUN   TestNavigate
=== RUN   TestNavigationEntries
=== RUN   TestNavigateToHistoryEntry
=== RUN   TestNavigateBack
=== RUN   TestNavigateForward
=== RUN   TestStop
=== RUN   TestReload
=== RUN   TestCaptureScreenshot
=== RUN   TestAddOnLoadScript
=== RUN   TestRemoveOnLoadScript
=== RUN   TestLocation
=== RUN   TestTitle
=== RUN   TestNodes
=== RUN   TestNodeIDs
=== RUN   TestFocusBlur
=== RUN   TestDimensions
=== RUN   TestText
=== RUN   TestClear
=== RUN   TestClear/test_0
=== RUN   TestClear/test_1
=== RUN   TestClear/test_2
=== RUN   TestClear/test_3
=== RUN   TestClear/test_4
=== RUN   TestClear/test_5
=== RUN   TestClear/test_6
=== RUN   TestClear/test_7
=== RUN   TestClear/test_8
=== RUN   TestClear/test_9
2017/02/22 16:34:55 error: pool could not start runner on port 9000: fork/exec : no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e0886]

goroutine 34 [running]:
testing.tRunner.func1(0xc420108dd0)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x8667e0, 0xb35770)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/knq/chromedp.(*CDP).Wait(0x0, 0x0, 0xc420049ca8)
	/home/idawson/gohome/src/github.com/knq/chromedp/chromedp.go:140 +0x26
github.com/knq/chromedp.(*Res).Release(0xc420102740, 0x0, 0x0)
	/home/idawson/gohome/src/github.com/knq/chromedp/pool.go:148 +0x53
github.com/knq/chromedp.(*Pool).Allocate(0xc4200189b0, 0xb12f60, 0xc420015400, 0x0, 0x0, 0x0, 0x0, 0xb0dfa0, 0xc42010c930)
	/home/idawson/gohome/src/github.com/knq/chromedp/pool.go:88 +0x58b
github.com/knq/chromedp.testAllocate(0xc420108dd0, 0x8e8405, 0x9, 0x10)
	/home/idawson/gohome/src/github.com/knq/chromedp/chromedp_test.go:15 +0x75
github.com/knq/chromedp.TestClear.func1(0xc420108dd0)
	/home/idawson/gohome/src/github.com/knq/chromedp/query_test.go:212 +0x6f
testing.tRunner(0xc420108dd0, 0xc420104220)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/knq/chromedp	0.008s

**Comment by kenshaw** [comment]
You're missing headless_chrome on the command line. It needs to be somewhere in your PATH. You can download a pre-compiled version of headless_shell here:

https://storage.googleapis.com/docker-chrome-headless/headless_shell-58.0.3019.2.tar.bz2
