### ISSUE TITLE
Add example mimicking `wget --mirror`-like functionality?

### ISSUE THREAD

**Issue by PaulCapestany** [knq/chromedp#35]
So, I'll admit that I haven't had a chance to dig very deeply into the code/docs of chromedp much yet, but from my cursory look at the current [examples](https://github.com/knq/chromedp/tree/master/examples), it didn't really seem like any covered one of the first use-cases for this awesome repo that came to my mind: [`wget --mirror`](https://www.gnu.org/software/wget/manual/html_node/Very-Advanced-Usage.html#index-mirroring)-like functionality.

Unless I've misunderstood what I've come across so far, chromedp could be great for mirroring websites much like `wget -m` does (recursively requesting all links to download all assets locally), with two additional amazing benefits: 

1. free/built-in concurrency for faster results (hooray for Go!)
2. the ability to actually execute javascript (i.e. mimic human-using-browser types of behaviors)

Just wanted to throw this out there to see if it might make for a valid use-case/example for chromedp. Either way, super cool repo, thanks for putting it out there :)

**Comment by kenshaw** [comment]
That's an interesting idea, and I'm definitely thinking of adding a simple example that "crawls" pages in general. It wouldn't be difficult to implement this.

**Comment by kenshaw** [comment]
After thinking about this some more, this is really left to a separate package / project, as I'd like to keep `chromedp` focused on "driving" Chrome + the debugging protocol. When you start getting into "crawling" kind of functionality, you really need significantly more advanced logic / behavior than what I think `chromedp` should be providing.

**Comment by DeadNumbers** [comment]
it would be a cool package/project :+1:

**Comment by mvdan** [comment]
If anyone wants to contribute, a PR in the [examples](https://github.com/chromedp/examples) repo is welcome. But it's unlikely we'll have time to work on this ourselves.
