### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by crackcomm** [knq/chromedp#46]
Tends to eat 400% CPU

Probably caused by https://github.com/knq/chromedp/blob/8eb44961e2c3fbb7b3b302184114c2eb2059c4b8/handler.go#L397

[Flame graph](http://ipfs.io/ipfs/Qme5e7xeEix5hYR1LhzLjihBV3xYWBegb7N22QEA2d1bY7)

**Comment by kenshaw** [comment]
We've removed this specific context creation. I am in the middle of finishing up the revamp to the context based parameters, and thus this one was no longer needed.
