### ISSUE TITLE
Provide a headless Chrome Docker image

### ISSUE THREAD

**Issue by derekperkins** [knq/chromedp#5]
@clanstyles Could you provide the compiled headless Chrome Docker image you mentioned in #2? I think building in connection options for that would help people, especially if they don't have to compile canary themselves.

**Comment by derekperkins** [comment]
I'm planning to run this inside of Kubernetes as an autoscaling deployment, so my intention is to package a small Go binary in the same container as Chrome that will use cdb to drive Chrome and act as a standalone microservice.

**Comment by clanstyles** [comment]
I'll copy what I said in #2 

```
I'll try to get something working shortly, I have a few other things on my plate in front of me.

The largest issue with all of these seems to be that they're not thread safe. You end up waiting for "idle time" to be able to create another action.

https://github.com/yukinying/chrome-headless-browser-docker is an example of a chrome headless browser
```

**Comment by kenshaw** [comment]
I published a public Docker image:

https://hub.docker.com/r/knqz/chrome-headless/

**Comment by Mathiou04** [comment]
> I'm planning to run this inside of Kubernetes as an autoscaling deployment, so my intention is to package a small Go binary in the same container as Chrome that will use cdb to drive Chrome and act as a standalone microservice.

@derekperkins Did you manage to do this? I am currently struggling at trying to achieve this behaviour.

**Comment by derekperkins** [comment]
Yes, it's working. What are you having issues with?
