### ISSUE TITLE
How to reuse already opened chrome instance

### ISSUE THREAD

**Issue by honzajde** [knq/chromedp#51]
Is it possible to reuse chrome window that was started before my go program?

**Comment by kenshaw** [comment]
Yes, if you launch Chrome using the `--remote-debugging-port` command line option, you can pass the `WithTargets` option to the `chromedp.New` func. This works in conjunction with `WatchPageTargets` from the `chromedp/client` package.

Check out the `examples/headless/main.go` for the full demonstration of the API, but here's the relevant bit copy/pasted from that example:

```go
     // create context
      ctxt, cancel := context.WithCancel(context.Background())
      defer cancel()
  
      // create chrome
      c, err := cdp.New(ctxt, cdp.WithTargets(client.New().WatchPageTargets(ctxt)), cdp.WithLog(log.Printf))
      if err != nil {
          log.Fatal(err)
      }
```

**Comment by 5k3105** [comment]
Sorry to comment on a closed topic.

So if I have a chrome window already open, say using `chrome.exe --remote-debugging-port=9222`

then code like:

```go
package main

import (
	"context"
	"log"
	"github.com/chromedp/chromedp/client"
	"github.com/chromedp/chromedp"
)

func main() {
	var err error

	// create context
	ctxt, cancel := context.WithCancel(context.Background())
	defer cancel()

	// create chrome
	c, err := chromedp.New(ctxt, chromedp.WithTargets(client.New().WatchPageTargets(ctxt)), chromedp.WithLog(log.Printf))
	if err != nil {
	  log.Fatal(err)
	}

	targets := len(c.ListTargets())
	
	println(targets)
	
}
```

should print `1` to the console when run?

I get `timeout waiting for initial target`
