### ISSUE TITLE
Support for --headless 

### ISSUE THREAD

**Issue by kryptodev** [knq/chromedp#52]
https://news.ycombinator.com/item?id=14101233

Hi, just wishing to know if headless support is guaranteed in relation to the aforementioned link. It's a new feature on chrome.

Thank you.

**Comment by kenshaw** [comment]
Yes, `--headless` is passed as an option when used with the `chromedp/runner` package. You can additionally also pass your own command line flags. Note that most of the development of chromedp has been done in conjunction with `headless_shell` or headless Chrome.

**Comment by prasanna-munnangi** [comment]
@kenshaw , is it possible to generate a pdf from a html file using ChromeDp runner options?

**Comment by kenshaw** [comment]
Yes, the Chrome Debugging Protocol supports the `Page.printToPDF` command. Please see here: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
