### ISSUE TITLE
Cannot close a target or new target to avoid reuse previous opened page in headless mode

### ISSUE THREAD

**Issue by wangadong** [knq/chromedp#56]
Hi,

When I use headless mode, if the tag wasn't properly shutdown, the page target will be there forever and I couldn't clear the cookie to isolate the test cases. The CloseByID method isn't implemented, and AddNewTarget is also unusable as it will panic and return some syntax error. 

I'm wondering if there's a way to initialize a new target everytime before I run a test case.

Thanks,
Xindong

**Comment by kenshaw** [comment]
It's not really possible to reuse headless_chrome instances. You should shutdown the process and create a new one. If you're doing any kind of automated testing / profiling / scraping, please refer to the `chromedp.Pool` type that helps with setting up / tearing down multiple Chrome processes.
