### ISSUE TITLE
Chromium support

### ISSUE THREAD

**Issue by budkin** [knq/chromedp#6]
```
$ go run main.go
2017/01/27 11:58:47 fork/exec /usr/bin/google-chrome: no such file or directory
exit status 1

```

**Comment by kenshaw** [comment]
This is on Linux? You can specify the specific location to the Google Chrome path using chromedp.WithRunnerOptions(runner.Path("/path/to/chrome"))

**Comment by budkin** [comment]
yeah, I just made a symlink to chromium in /usr/local/bin, and everything works great
