### ISSUE TITLE
Is it possible to use with Chrome as background process?

### ISSUE THREAD

**Issue by LeMoussel** [knq/chromedp#61]
Is it possible to use `chromedp` with Chrome headless as background process ?
eg.

> 
> // https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
> // --disable-gpu currently required, see link above
> google-chrome --headless --hide-scrollbars --remote-debugging-port=9222 --disable-gpu &

If yes, can you explain how can I do that?

**Comment by kenshaw** [comment]
Yes, you need to manually run chrome, and then you can connect to an existing chrome instance by manually creating the client and passing the targets with the `WithTargets` option. Please see the `examples/headless/main.go` file for an example of how the API is used.
