### ISSUE TITLE
chrome.exe": file does not exist

### ISSUE THREAD

**Issue by CodyGuo** [knq/chromedp#65]
2017/06/04 17:18:51 exec: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe": file does not exist

**Comment by lewgun** [comment]
...

	execPath := `C:\Users\mshz\AppData\Local\Google\Chrome\Application\chrome.exe`
	// create chrome instance

	opts := cdp.WithRunnerOptions(
		runner.ExecPath(execPath),
		runner.UserDataDir(`d:\temp`),
		runner.Port(12316),
	)
	c, err := cdp.New(ctxt, cdp.WithLog(log.Printf), opts)
	if err != nil {
		log.Fatal(err)
	}
... @CodyGuo

**Comment by CodyGuo** [comment]
OK, thank you.
