### ISSUE TITLE
How to open a new tab (and use it)

### ISSUE THREAD

**Issue by honzajde** [knq/chromedp#66]
I am looking at cdp package and no way I can find it;)

**Comment by MrSaints** [comment]
Create a new target, create a handler from the target, and then initialise it for use:

```
	client := cdpclient.New()
	t, err := client.NewPageTarget(ctx)
	if err != nil {
		return err
	}

	h, err := cdp.NewTargetHandler(t, log.Printf, log.Printf, log.Printf)
	if err != nil {
		return err
	}

	if err := h.Run(ctx); err != nil {
		return err
	}
```

**Comment by kenshaw** [comment]
As @MrSaints has described.

**Comment by KristinaEtc** [comment]
Is it possible to create a new private tab?

**Comment by MrSaints** [comment]
@KristinaEtc I don't think so, but you can simply disable cookies (or rather, delete them), and disable caching. You'll get a similar behaviour to Incognito.
