### ISSUE TITLE
Unable to set extra HTTP headers

### ISSUE THREAD

**Issue by MrSaints** [knq/chromedp#68]
The `network` package's `SetExtraHTTPHeaders` method accepts a type of `Headers`. But it is an empty struct with no fields. It seems like it should really be a `map[string]interface{}` if there are no properties in the protocol definition. Otherwise, how can we set extra HTTP headers?

**Comment by alexanderkrupin** [comment]
Also have similar problem. Please fix it 👍

**Comment by kenshaw** [comment]
Fixed. Please review and let me know if it works for your purposes.
