### ISSUE TITLE
timeout waiting for initial target when testing the demo

### ISSUE THREAD

**Issue by lagenar** [knq/chromedp#7]
Hi there, when I try the demo using ubuntu 16.04 I get the following error message.

2017/01/27 09:48:21 timeout waiting for initial target
exit status 1

I think it may be related to the library not finding chrome's executable?

When I check the path of chrome I see the following:

lucas@lucas-notebook:~/go$ ls -lah /usr/bin/google-chrome
lrwxrwxrwx 1 root root 31 abr 25  2016 /usr/bin/google-chrome -> /etc/alternatives/google-chrome

**Comment by kenshaw** [comment]
Could you give me more information about your environment? You can specify the path to Chrome using:

```go
ctxt, cancel := context.WithCancel(context.Background())
defer cancel()
c, err := chromedp.New(ctxt, chromedp.WithRunnerOptions(
    runner.Path("/path/to/chrome"),
))
```

**Comment by jonaspu** [comment]
I encounter the same error.
My environment:
Ubuntu 16.04 + chromium-browser

I'm not sure if the problem is chromium, but even giving the path does not help.

**Comment by daltonfury42** [comment]
@jonaspu Mind sharing how you fixed it? `no-sandbox` flag?
