### ISSUE TITLE
Unable to distinguish 404 (and failed connections) from 200

### ISSUE THREAD

**Issue by kjk** [knq/chromedp#73]
I'm trying to write a basic recursive link checker.

I've been unable to distinguish valid 200 responses from 404 and even the case when connection fails (e.g. trying to Navigate to "https://domain.not-existant-at-all.com".

In both cases I get valid dom to query (for 404 it's what website returns, for connection failure it's Chrome's "can't connect" page).

I've looked at the examples and perused the code and didn't find a way to access this information.

It looks it would require looking at EventNetworkResponseReceived and associated EventResponseReceived and it's Response.Status.

I know this is tricky, because dom tree doesn't necessarily correspond to a single http request, but in common case when it does, maybe the API could expose Response struct associated with a given frame and a way to access it?

**Comment by kenshaw** [comment]
You would need to write a high-level network manager. Currently, there is not "out-of-the-box" support for this, however I recognize that is a glaring oversight (for what it's worth, for the ways that `chromedp` is being used on our end, we have a fairly good expectation of whether or not a page exists).
