### ISSUE TITLE
ScrollIntoView surprisingly does scrollIntoViewIfNeeded

### ISSUE THREAD

**Issue by pwaller** [knq/chromedp#83]
I spent a little while pondering why `cdp.ScrollIntoView` was not working as I expected from my knowledge of what it does in JavaScript. The behaviour I saw was that it was not scrolling when I was expecting it to - it was just behaving as though scroll was a no-op. I almost gave up trying to get this to work, believing it to just be broken. But I went hunting:

```go
// ScrollIntoView scrolls the window to the first node matching the selector.
func ScrollIntoView(sel interface{}, opts ...QueryOption) Action {
// ...
        err = EvaluateAsDevTools(fmt.Sprintf(scrollIntoViewJS, nodes[0].FullXPath()), &pos).Do(ctxt, h)
// ...
```

Turns out is is documented on [`scrollIntoViewJS`](https://github.com/knq/chromedp/blob/fa151e8cf57be2f7cdb3f9b8bf4011d4f015e66c/util.go#L49-L55):

```go
	// scrollIntoViewJS is a javascript snippet that scrolls the specified node
	// into the window's viewport (if needed), returning the actual window x/y
	// after execution.
	scrollIntoViewJS = `(function(a) {
		a[0].scrollIntoViewIfNeeded(true);
		return [window.scrollX, window.scrollY];
	})($x('%s'))`
```

I suggest two possible routes forward:

1. Simply do `a[0].scrollIntoView`. This should be pretty much backwards compatible, it just means that some things which didn't need the scroll now have the overhead of scrolling. At least bugs like the one I encountered would be averted. Anything which really needs `IfNeeded` for the performance benefit of avoiding unnecessary scrolls can introduce a new `ScrollIntoViewIfNeeded` which does it. I can't at this point think of circumstances which would immediately break with the additional scrolling.

2. If you don't want to change the existing function, at least it should be documented that `ScrollIntoView` is actually `scrollIntoViewIfNeeded` on the function. I like this change less, because it's still surprising. I also actually need `scrollIntoView`, not `...IfNeeded`.

 My use-case is to take a full-viewport screenshot, but only starting from a specific element. This element happens to be visible in the viewport prior to the scroll request (so `...IfNeeded` does not scroll), but I need the elements which are below this element to be scrolled into the viewport too.

**Comment by kenshaw** [comment]
Originally we were using `scrollIntoView` -- it didn't work properly with what we were doing. It's just a javascript function call -- I would suggest writing a similar action to call `chromedp.EvaluateAsDevTools()`...
