### ISSUE TITLE
Can anyone share a practical example of a  parser using chromedp? 

### ISSUE THREAD

**Issue by SvitlanaShepitsena** [knq/chromedp#88]
Hi
Thank you for a great job you did. I have gone via all example folder, but I am pretty new to Golang, so I cannot figure things out  by reading source code and I got stuck when I need to switch to another chrome tab but it is one of :-) . Maybe somebody has a non-commercial parser using chromedp. 

Thank you,
Svitlana

**Comment by kenshaw** [comment]
I'm not really sure what you mean by creating a parser?

**Comment by SvitlanaShepitsena** [comment]
Thank you for your answer, Kenneth. 
I meant I need more examples. I started to use chromedp, but I have problems in understanding some parts. I wonder maybe you have a practical example - you can share with me. I am trying to write a scrapper that will log to MLS,  open from menu another service and get some statistics.

I tried to find in github who uses chromedp but in public repositories, I found very few... 

Thank you

**Comment by SvitlanaShepitsena** [comment]
Kennesh, I am sorry for annoying but if you have some examples of using chromedp can you please send me them? I have issues with iframes, etc.
 
Or if you do not have - that's fine just let me know - I need to make a decision which way to go and both answers are fine with me. 

Thank you,
Svitlana

**Comment by kenshaw** [comment]
There are examples in the [examples](https://github.com/knq/chromedp/tree/master/examples) directory. I don't think I can really help you much more beyond that. Using `chromedp`, Selenium, or any other browser driving solution will require a large amount of knowledge about how browsers and the DOM work. Unfortunately, the documentation currently available for `chromedp` is fairly limited at this time.
