### ISSUE TITLE
Add Options after New

### ISSUE THREAD

**Issue by suntong** [knq/chromedp#96]
Is it true that currently `Option`s are added only during `New()`?

How to add `Option`s after calling `New()`? I want, 

```
// create chrome instance
c, err = cdp.New(ctxt)

// this -> 
c  = cdp.AddOptions(cdp.WithErrorf(log.Printf))
```

Is it possible? Thx.

**Comment by kenshaw** [comment]
The Go way of doing this is the following:
```go
err := cdp.WithErrorf(log.Printf)(c)
if err != nil { /* ... */ }
```
Note that the options are just functions with a common signature that modifies the original instance. It's also worth mentioning that some option signatures in Go packages return an error.

**Comment by suntong** [comment]
thanks. 

Note to myself, the above practice is called, 

[**decorator pattern**](https://github.com/bahlo/go-styleguide#use-decorator-pattern)
