### ISSUE TITLE
QueryOption for Waiting

### ISSUE THREAD

**Issue by suntong** [knq/chromedp#98]
All Waiting operation have `QueryOptions` parameter. If I'm writing a library, and don't know exactly what the selected element is, be it ID, or NodeID, then what I should set for such `QueryOptions` parameter? 

Would it be `ByQuery` or `ByQueryAll `, or `BySearch ` or anything else?

I mean, if the css is `xxx#id` then we know the selection is by ID; whereas if the css is `xxx.id` then we know the selection is by class, etc. So what exactly this `QueryOptions` parameter is for?

**Comment by kenshaw** [comment]
The `By*` functions simply change which node selection mechanism is used by `chromedp` and affects how the initial search is performed. The following is a summary of some of the various `By*` funcs:

`BySearch` wraps the  `DOM.performSearch` and `DOM.getSearchResults` API calls (please see the Chrome Debugging Protocol documentation)
`ByQuery` wraps the `DOM.querySelector` API call (please see CDP documentation)
`ByQueryAll` wraps the `DOM.querySelectorAll API call (please see the CDP documentation)

The following are higher order convenience utilities:
`ByNodeID` allows one to specify the actual node by its internal `cdp.NodeID` value (ie, when found/selected via an alternate method), but simply uses the `DOM.requestChildNodes` API call
`ByID` allows one to specify the targeted node based off a matching CSS `#id` selector -- this is a wrapper around `ByQuery`

You can use the `BySearch` and `ByQuery` calls to basically perform the various CSS or XPath style selectors. Please see the appropriate CDP documentation.

**Comment by kenshaw** [comment]
Also, to answer your original question, `QueryOptions` modify how the selector is applied to the node search. The node search type is specified by the various `By*` options.
